name: Node.js CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # We’ll pick one Node version for the build and deploy
    # If you want multiple versions for testing, keep a separate job for that
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      # Upload the built files (usually in `dist`) for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist  # adjust if your build output directory is different

  deploy:
    # Only run deploy job on push (not on PRs) and depends on build
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
